Set both caller and self as controller by default
dfinity/cycles-wallet pull request #110
Opened 2021-11-19 21:03 UTC by adamspofford-dfinity

2021-11-19 22:02 UTC, ericswanson-dfinity commented on wallet/src/lib.rs
> +        let mut settings = normalize_canister_settings(args.settings)?;
Please take a look at create_wallet(), which calls this method settings specifically modified in order to have no controllers set.

2021-11-19 22:05 UTC, ericswanson-dfinity requested changes
Would you please add a little information (in the PR description) about context?

For example, will we also be modifying dfx to allow configuring it such that all newly canisters will have as controllers the wallet, the dfx identity, and a configured II identity?  If so, this code path won't be taken in practice, so it would be useful to know in which cases it would be taken.

2021-11-19 22:05 UTC, ericswanson-dfinity commented on wallet/src/lib.rs
> +        let mut settings = normalize_canister_settings(args.settings)?;
Please take a look at create_wallet(), which calls this method settings specifically modified in order to have no controllers set.

2021-11-19 22:12 UTC, adamspofford-dfinity commented
I have no idea what the changes will be on the DFX end, Kyle said to just implement it on the wallet level for now.

2021-11-20 00:29 UTC, ericswanson-dfinity requested changes
Let's start by updating the e2e tests and go from there

2021-12-04 01:31 UTC, ericswanson-dfinity approved these changes

2021-12-04 01:47 UTC, merged